---

language: node_js

node_js: lts/*

script:
  - npm run lint
  - npm run test
  - npm run build

deploy:
  - provider: script
    skip_cleanup: true
    script: npm run release
    on:
      repo: system76/pop-vue
      branch: master

  - provider: pages
    skip_cleanup: true
    github-token: $GH_TOKEN
    local-dir: docs
    keep-history: false
    fqdn: pop-vue.origin76.com
    on:
      repo: system76/pop-vue
      branch: master
